# Generated by Django 2.2.6 on 2019-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
        ),
    ]
