# Generated by Django 2.2.6 on 2019-12-14 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_auto_20191213_1832'),
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='organization',
            field=models.ForeignKey(default='n/a', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(default='nil', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
