# Generated by Django 2.2.6 on 2019-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='timezone',
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_num',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
    ]
