# Generated by Django 2.2.6 on 2019-12-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20191213_1832'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='org_id',
        ),
        migrations.AddField(
            model_name='camera',
            name='organization',
            field=models.ForeignKey(default='n/a', on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
