# Generated by Django 3.0 on 2019-12-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='short_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
